version: '3'
services:
  smartsearch-api:
    container_name: smartsearch-api
    image: 'spacelama/api-go:dev'
    depends_on:
      - smartsearch-db
    ports:
      - "9000:9000"
    networks:
      - frontend
      - backend
  smartsearch-db:
    image: 'mongo:latest'
    container_name: smartsearch-db
    ports:
      - '27017:27017'
    volumes:
      - './mongo/configdb:/data/configdb'
      - './mongo/db:/data/db'
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge