apiVersion: v1
kind: Namespace
metadata:
  name:  spacelama
---
apiVersion: v1
kind: Secret
metadata:
  name:  spacelama-administrators-secret
  namespace: spacelama
stringData:
  administrator.json: ewogICAgImFkbWluIjogIkx4Q1RES2llOTh2ZGJOY1pSRFFRWjdBZzFyVmgydjY5TUFvUllhakkiLAogICAgImFkbWluMiI6ICJMeENUREtpZTk4UktGUzUzdmRiTmNRUVo3QWcxclZoMnY2OU1BakkiCn0=
---
apiVersion: v1
kind: Secret
metadata:
  name: spacelama-gcp-service-account-secret
  namespace: spacelama
stringData:
   gcp-service-account.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3BhY2VsYW1hIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNThhNzY0N2UyZTU5NTQ2NzgzYWI5NGNkZGVjYjQwZWRkZTM3YjUzNSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZ3SUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2t3Z2dTbEFnRUFBb0lCQVFDMyt5VVVNdngyZ0d1RlxuUnJ1RUJScGdzOXU2cFhjeENXN0tlWkxpQkZIWmh0N2NDVDNKaXBlclJUaGJXUE1lNTJhOG1DbzJ3MXhWdVVGWlxuRnFWUk9Ka0tvNGFoR1Rqc0JuZmUwdnRESlBVM2Z5cnNXK1pBQ3ZVU3dOTWxiOXlsMzNaTlZSMktlUlBoR3RaTVxuc1hoaXYxSW5tREZpbnN5T0FxQTkzUW1SRE5nU2VzU0o2SndlRG1xMyttd1d5cS84VU52Tk4veS9Kd1lPT1JIbFxud21WZGZ3WDNic3NuZHYwRmtYa3AvRVhrcjI1RGZRTjBGMHhOa002dUE5dzZyRlhONElrb25Ja2k0QWNHV0VnZlxubVpyZllZQ25LOUo1ZXhEckgvVHhJRjNKSGoyMCt5SEJHd09RYm5vVWhQSkNSRTg3aURwc2k0UUMxeCtwVGJBaFxuYlFWcXlzRnJBZ01CQUFFQ2dnRUFPdmorbnFYbE5OcmZIQjViRnV0SDFEMXlyalpCcVc4N214MHpEczJScXVkSFxuWWtKNEVyVWcvcDQyZlZsYXZNb3hyVHdkTSthVkgwazlnQi81SjdxN202UmxFQmgwblh0SlN4eFh1K01KMHhzcFxuR0JBeEV0QXdWQzJJd05SRlpzbmxNczZZcEgxQStRUFFNMDhqcG90cSt4UVdxR1Q4Ym55Ni9ubHVpcGNTWDRGOFxua2lOaDZ0QXI2VDVxZHhWNkkvV2lybU9oQ09wclJyL3g2MDhLcnc1b3kxc2tmNG5XV3hYNHgxOEVqQmxOWUN1bFxueVRJMC9EbDVQck5Yd3ZzU1QxNElEdC9MamJ4Y1dlc3NCdDRjNitxMWM1QVhpTHZOSU53R3dLR3JMckN3YjMzUFxuUkZOL2xvRHlDK0tRVjZUUjdrMUpiaUU2RjFjQUUwU0kvdWp5SFBxNStRS0JnUUR6eE9XaUp4Vm1QTmJBTjZLc1xuWTlFRVdZVXdTZFZvQzlLQnQrd0Z4elowcnhSWHBlL1kzb3UwTEgwcXUrL3JTVGZtb1ZVcExPaC94bEZ5WFF0S1xucTlYNnIxY2ZPemZIUkNxRFZTOHdGSE0vZXY1Vjl5c2YyZVFKRWtmWS9NRUxwazExZitPazZwRW03VlZaNExqS1xudjNjNUsvclNDK0YwQWpLNFVJc09nZTM1VFFLQmdRREJOa3dPdzdwUFFIVXdtWnZ3ejZWSVc5aUk2aDY4a2lMK1xuV25QTUxkSUZGODJzN3FjMGVKSHRWZE44WG1nZCtJb0tHMXBYNDdVbG9LZTRiWGVraDd1U09uQ1Z2c0s2cEpWelxuamptc2ovb3hXZTVZN1VTeC9weUE0TUVBVUw4aTN2RDAvbW5KTkxVS3dYSkFqUStKd29hTzdTZEVqM0ozYmtLdVxuS3dPY1k4MEpsd0tCZ1FDSU5PMkdoRVlkd1VMUlZvVHJ4RDVIS3VvVHlEMlpESG9NQjBPM0dzL2Z0UEF0NVVjMlxuSzJ0dU9pbWFGamNCaGdEWk9pNUdlcFJTeVBJN2I2ZmVpbE5lNWxoTTJCN2JsY2dYYUNLY3YrQ0JpT3pTQmZDdlxudEdVSmVKQnl1dy8ydlc2c2g5QWdGdjBSL2l6aHNvSXVyM3NqaytKck9UNDVQdjB1SmJyOVdUWXFSUUtCZ1FDQlxuRjlKQm15MEVmc0RPTkJRcEZkUU5RTEN3Nmh5WFNkenZyV2ZwYUVRRyt4eUZDdi9VNHlvOU5UY1V4Yzh6RnpqRFxuLy9xZzlwZTJDRjJIc0R4Y1JnUmhjNEo5eXZNNDJYYXh1cmwyUHN5ZjVNS0gwQ0F4L1RoOE02OUFrckxpamFyWlxuUnBOUHlGT2VXQm9LWHpXZWljWjJBS1pYL0xBeWRBMUJhYVFEL2ZxbENRS0JnUUNGL0ZWaUR3V055MVVqOEZtS1xuOUNQTkpXWXhLOEx5bU94emEwa2YvczlGdGFaa09lU1dhVExJOGJUajI1SndqZ2tHOWMzZ2FEbWhGTXpOTU95Q1xuVzZGSXdQTHFLdVB4ZmZHeEtBRUw0R0MveGJQcGpIUXhFZ2laZHByQmVDM3F0TVFyTGdIZUZBRHBuZG5ZYW9IR1xuSjlrUHJqR0N5WExITE5vTVlUeGpHazJLQmc9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogInNtYXJ0c2VhcmNoLXNlcnZpY2UtYWNjb3VudEBzcGFjZWxhbWEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwODA0MDA5Nzk2MzYyNDYwNzcwIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9zbWFydHNlYXJjaC1zZXJ2aWNlLWFjY291bnQlNDBzcGFjZWxhbWEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0= 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: spacelama
  name:  spacelama-api
  labels:
    name:  spacelama-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  spacelama-api
    spec:
      containers:
      - image:  spacelama/api-go:firestore
        imagePullPolicy: Always
        name:  spacelama-api
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  80
          name: gingonic
        volumeMounts:
        - name: gcp-service-account
          mountPath: "/credentials/gcp-service-account.json"
          readOnly: true
        - name: administrators
          mountPath: "/credentials/administrators.json"
          readOnly: true
      volumes:
      - name: gcp-service-account
        secret:
          secretName: spacelama-gcp-service-account-secret
      - name: administrators
        secret:
          secretName: spacelama-administrators-secret
---
  kind: Service
  apiVersion: v1
  metadata:
    namespace: spacelama
    name:  spacelama-api
  spec:
    selector:
      name:  spacelama-api
    type:  LoadBalancer
    ports:
    - name:  gingonic
      port:  80